# Use a Node.js image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install curl for healthcheck and npm dependencies
RUN apk add --no-cache curl && npm install

# Copy the rest of the application code
COPY . .

# Expose the Angular CLI port and the app port
EXPOSE 4200

# Start the Angular development server
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
