services:
  # CoreAPI (Now uses Simple Auth)
  coreapi:
    build: ./CoreAPI
    container_name: webcontrol-coreapi-1
    environment:
      - JWT_SECRET=your-secret-key-change-in-production
    networks:
      - app-network
    restart: unless-stopped

  # Nginx (Frontend + Reverse Proxy)
  nginx:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - coreapi
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
