core_config_version: 0
host: "0.0.0.0"
port: 3567
access_token_validity: 3600
refresh_token_validity: 144000

# Database configuration
postgresql_connection_uri: "postgresql://supertokens:supertoken_pass@postgres:5432/supertokens"

# CORS configuration
cors:
  allow_origin: "http://localhost"
  allow_headers: "content-type,rid,fdi-version,authorization,anti-csrf,st-auth-mode"
  allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
  allow_credentials: true
