# WebControl Users and Groups Configuration

[groups]
# Define groups with their lecturers and boards
[groups.group1]
name = "Energy Systems Lab Group 1"
description = "Main laboratory group for energy management exercises"

# Lecturer for this group
[groups.group1.lecturer]
username = "lecturer1"
password = "lecturer123"
name = "Dr. John Smith"
email = "john.smith@university.edu"
department = "Computer Science"

# Boards belonging to this group
[[groups.group1.boards]]
username = "board1"
password = "board123"
board_id = 4001
name = "Solar Panel Board #1"
type = "solar"
location = "Lab Station A"

[[groups.group1.boards]]
username = "board2"
password = "board456"
board_id = 4002
name = "Wind Turbine Board #1"
type = "wind"
location = "Lab Station B"

[[groups.group1.boards]]
username = "board3"
password = "board789"
board_id = 4003
name = "Battery Storage Board #1"
type = "battery"
location = "Lab Station C"

# Additional group for future expansion
[groups.group2]
name = "Energy Systems Lab Group 2"
description = "Secondary laboratory group"

[groups.group2.lecturer]
username = "lecturer2"
password = "lecturer456"
name = "Prof. Maria Garcia"
email = "maria.garcia@university.edu"
department = "Physics"

[[groups.group2.boards]]
username = "board4"
password = "board111"
board_id = 4004
name = "Solar Panel Board #2"
type = "solar"
location = "Lab Station D"

[[groups.group2.boards]]
username = "board5"
password = "board222"
board_id = 4005
name = "Gas Turbine Board #1"
type = "gas"
location = "Lab Station E"
